# Generated by Django 5.1.11 on 2025-09-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Просмотры"
            ),
        ),
    ]
