# Generated by Django 5.1.11 on 2025-09-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contactinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="map_embed",
            field=models.TextField(
                blank=True, default="", verbose_name="Карта (iframe)"
            ),
        ),
    ]
